### ISSUE TITLE
Line 46 error

### ISSUE THREAD

**Issue by Bastien250** [LG-Experiment/Scripts#1]
Hello, 

I have this error when I use the script : "Line 46: Cannot read properties of undefined (reading ‘0’)"

Why ? any help please ?

I correctly set the key in excel. I have automate tab. I am working with office 365 online.

Thanks for help.

**Comment by mmustafaaslan** [comment]
I assume the error occurred because you have not created a paid account yet.

**Comment by Bastien250** [comment]
ok thanks 
"paid account" in chatgpt ? 
I use office 365 online

**Comment by mmustafaaslan** [comment]
Yes, you will see it on OpenAI. As I mentioned its my guess, please try and let under this topic.

**Comment by Bastien250** [comment]
ok thanks
Maybe the autor [LG-Experiment](https://github.com/LG-Experiment) could have a solution

**Comment by lucasozim** [comment]
Same error "Line 46: Cannot read properties of undefined (reading ‘0’)"  Please @LG-Experiment could you assist witht this.

**Comment by LG-Experiment** [comment]
I tried to replicate this error and the only way I got it to trigger is if the API code is incorrect. Perhaps you can try to remove your API code and re-generate a new one. If anyone else has any insights please share.

**Comment by Bastien250** [comment]
ok thanks but still error. I think this is my office 365 with pb...

**Comment by STAdvisory** [comment]
I have the exact same error. I have just created new API. still no luck.

**Comment by douglasshepherd** [comment]
Hey all, I had this same issue at first.  I didn't realize that my OpenAI account trial had expired in December and so I did have to fund the account, per the comment by @mmustafaaslan .  I suggest checking that you have tokens available in OpenAI if you are having this issue.

**Comment by Bastien250** [comment]
Hello 
Thanks I tried with a new account in Chatgpt and a new key API in excel and it is working :) 
Thanks
