### ISSUE TITLE
"Script is running" but nothing happens

### ISSUE THREAD

**Issue by SystemsModelling** [LG-Experiment/Scripts#5]
Windows 10, office 365. I pasted in the .ts and put in the apiKey. I can run it, no compile errors, but it never terminates.
Pity there is no way to single step I Officescript code.
I put in a console.log but nothing happened.

**Comment by emrefurkanozshn** [comment]
Could you solve the issue?

**Comment by SystemsModelling** [comment]
Thanks  emrefurkanozshn, I had forgotten that post. I don't know what I did or what changed, but it did start working. I updated it to use the ChatGPT 3.5 API. My blog post is at 
https://sysmod.wordpress.com/2023/03/15/chatgpt-3-5-excel-script/

**Comment by emrefurkanozshn** [comment]
Thank you. Great content.
Do you know how to enable Automate tab in Excel maybe?
I already have it but my friend is missing it.

**Comment by SystemsModelling** [comment]
Does this help?https://techcommunity.microsoft.com/t5/excel/automate-tab-missing/m-p/1639670On 19 Apr 2023 15:14, emrefurkanozshn ***@***.***> wrote:
Thank you. Great content.
Do you know how to enable Automate tab in Excel maybe?
I already have it but my friend is missing it.
